name: Question
description: Use to submit a question or if you need help with using the mod. Use only if none of the other options are relevant.   
labels: ["question", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the following to submit a question
  - type: textarea
    id: the-question
    attributes:
      label: The question
      description: |
        What would you like to ask?
      placeholder: How do I target an item based on its damage value?
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Check the boxes in order to submit the issue
      options:
        - label: I checked the issues(both open and closed) and could not find a duplicate of my question
          required: true
